server:
  port: 30013

spring:
   datasource:
     url: jdbc:mysql://localhost:3306/video-service?useSSL=false
     username: root
     password: 123456
     driver-class-name: com.mysql.cj.jdbc.Driver

   servlet:
     multipart.max-file-size: 128MB
     multipart.max-request-size: 128MB

   main.allow-circular-references: true

   mvc:
     pathmatch:
       matching-strategy: ant_path_matcher

   application:
     name: video-service
   cloud:
     nacos:
       server-addr: localhost:8848 # nacos服务地址
     config:
       #服务器地址
       server-addr: localhost:8848
       # 配置文件格式
       file-extension: yml

mybatis:
  type-aliases-package: com.bilimili.video.dao
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

ecs:
  url: 10.193.208.112:30010
  # ecs.url = 120.46.53.94:8080
  # ecs.url = 10.193.208.112:8080
  bucket:
    # path: /usr/local/springboot/micro/
    path: D:/Bilimili/
# ecs.bucket.path = D:/Bilimili/

swagger:
  enable: true
  application-name: 鉴权配置中心接口
  application-version: 1.0
  application-description: 鉴权配置中心
