server:
  port: 30014

spring:
   datasource:
     url: jdbc:mysql://localhost:3306/msg-service?useSSL=false # 本地
     # url: jdbc:mysql://10.193.208.112:3306/msg-service?useSSL=false
     username: root
     # password: yinli03957170
     password: 123456
     driver-class-name: com.mysql.cj.jdbc.Driver

   servlet:
     multipart.max-file-size: 128MB
     multipart.max-request-size: 128MB

   main.allow-circular-references: true

   application:
     name: msg-service
   cloud:
     nacos:
       # server-addr: localhost:8848 # 本机本地
       server-addr: 10.193.208.112:8848 # docker中的nacos
#     config:
#       #服务器地址
#       server-addr: localhost:8848
#       # 配置文件格式
#       file-extension: yml
     gateway:
       globalcors:
         cors-configurations:
           '[/**]':
             allowedOrigins: "*"
             allowedHeaders: "*"
             allowedMethods: "*"
       default-filters:
         - DedupeResponseHeader=Vary Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

mybatis:
  type-aliases-package: com.bilimili.msg.dao
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

ecs:
  url: 10.193.208.112:30010
  # ecs.url = 120.46.53.94:8080
  # ecs.url = 10.193.208.112:8080
  bucket:
    path: D:/Bilimili/
    # path: /usr/local/springboot/micro/

# ecs.bucket.path = D:/Bilimili/