server:
  port: 30011

spring:
   datasource:
     url: jdbc:mysql://localhost:3306/user-service?characterEncoding=utf-8
     username: root
     password: 123456
     driver-class-name: com.mysql.cj.jdbc.Driver
   application:
    name: search-service
   cloud:
    nacos:
      server-addr: localhost:8848 # nacos服务地址
    config:
      #服务器地址
      server-addr: localhost:8848
      # 配置文件格式
      file-extension: yml

logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

ecs:
  url: 10.193.208.112:30010
  # ecs.url = 120.46.53.94:8080
  # ecs.url = 10.193.208.112:8080
  bucket:
    path: D:/Bilimili/
    # path: /usr/local/springboot/micro/

# ecs.bucket.path = D:/Bilimili/